[window]
	padding = { x = 3, y = 3 }

[font]
	normal = { family = "Terminus", style = "Regular" }
	size = 6

[colors.primary]
	background = "#090815"

[colors.normal]
	black = "#000000"
	red = "#ff0000"
	green = "#00ff00"
	yellow = "#ffff00"
	blue = "#0055ff"
	magenta = "#ff00ff"
	cyan = "#00ffff"
	white = "#ffffff"
