set shiftwidth=4
set tabstop=4
set clipboard=unnamedplus
set showtabline=2
set number

set completeopt-=preview

cabbrev make make!

set termguicolors
if !has('nvim') && !has('gui_running')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif
syntax on
filetype plugin indent on

set mouse=a
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
inoremap ( ()<Esc>i
inoremap [ []<Esc>i
inoremap " ""<Esc>i
inoremap ' ''<Esc>i
inoremap {<CR> {<CR>}<Esc>O

" swap j and k
nnoremap j k
nnoremap k j
vnoremap j k
vnoremap k j

nnoremap <Space> <Nop>
let mapleader = "\<Space>"

let g:netrw_liststyle = 3
let g:netrw_winsize = 11
let g:netrw_banner = 0
nnoremap <leader>e :Lexplore<CR>

call plug#begin()

Plug 'tpope/vim-sensible'
Plug 'itchyny/lightline.vim'
Plug 'bluz71/vim-moonfly-colors', { 'as': 'moonfly' }
Plug 'catppuccin/vim', { 'as': 'catppuccin' }
Plug 'mattn/vim-lsp-settings'
Plug 'justinmk/vim-syntax-extra'
Plug 'prabirshrestha/vim-lsp'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'

call plug#end()

inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() . "\<cr>" : "\<cr>"

let g:lsp_diagnostics_virtual_text_align = "right"
let g:lsp_diagnostics_float_cursor = 1

if executable('asm-lsp')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'asm-lsp',
        \ 'cmd': {server_info->['asm-lsp']},
        \ 'whitelist': ['asm', 's'],
        \ })
endif

colorscheme catppuccin_mocha
